// <auto-generated />
using BitGamb.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BitGamb.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191018064512_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("BitGamb.API.Models.Robot", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("consecWins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("robotName")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Robots");
                });
#pragma warning restore 612, 618
        }
    }
}
